# Generated by Django 4.2.26 on 2025-11-28 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aprendiz',
            fields=[
                ('document', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('birthdate', models.DateField(null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('program', models.CharField(max_length=50)),
            ],
        ),
    ]
